name: Publish Library

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Release build and publish
    runs-on: macOS-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
      deployments: write

    env:
      JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
      JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
      JRELEASER_GITHUB_USERNAME: ${{ github.actor }}
      JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
      JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
      JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Publish to MavenCentral
        run: |
          ./gradlew jreleaserConfig
          ./gradlew clean
          ./gradlew publish --continue
          ./gradlew jreleaserFullRelease --continue

  publish-release:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Releasing
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
